apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssi-tails-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssi-tails-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ssi-tails-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ssi-tails-server.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: data-{{include "ssi-tails-server.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssi-tails-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 6543
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath:  {{ .Values.volumeSettings.hostPath | default "/" | quote }}
              name: task-pv-storage
          env:
            - name: TAILS_SERVER_ADDRESS
              value: {{ .Values.tails.address | default "0.0.0.0" | quote }}
            - name: TAILS_SERVER_PORT
              value: {{ .Values.service.port | default "6543" | quote }}
            - name: TAILS_SERVER_LOG_LEVEL
              value: {{ .Values.tails.loglevel | default "info" | quote }}
            {{- include "helpers.list-env-variables" . | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
