# Default values for ssi-accreditation-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/my-digi-id/ssi-acmgt-ssi-accreditation-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.2.3"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  # Service account not needed and can cause issues with OpenShift
  create: false

## Default port exposed in image is 4200 - change if modified in image
service:
  type: ClusterIP
  port: 4200

ingress:
  enabled: false
  tls: 
  - hosts:
    - ssi-accreditation-ui.local
    secretName: tls-secret
  hosts:
    - host: ssi-accreditation-ui.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false

accreditation:
  url: 

keycloak:
  ## Must put /auth at end of url
  url:	
  realm:	
  clientID:	

env: {}
