apiVersion: v1
kind: Service
metadata:
  name: indy-network-monitor-{{ .Release.Name }}
  labels:
    app: monitor-{{ .Release.Name }}
    family: indy-network-monitor

spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: monitor-{{ .Release.Name }}

