# Default values for ssi-verification-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/my-digi-id/ssi-acmgt-verification-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.2.2"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  # Service account not needed and can cause issues with OpenShift
  create: false

## Default port expose in image is 4300 - change if modified in image
service:
  type: ClusterIP
  port: 4300

ingress:
  enabled: false
  tls: 
  - hosts:
    - verification-ui.local
    secretName: tls-secret
  hosts:
    - host: verification-ui.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false

verification:
  url: 
  qrBaseURL: 

keycloak:
  ## Must put /auth at end of url
  url:	
  realm:	
  clientID:	

env: {}
