{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ssi-aca-py.fullname" . -}}
{{- $tailsFullName := printf "%s-ssi-tails-server" .Release.Name -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ssi-aca-py.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- if $.Values.ingress.exposeAdmin }}
        - {{ $.Values.ingress.subdomainPrefix}}indy-admin.{{ $.Values.ingress.host }}
        {{- end }}
        - {{ $.Values.ingress.subdomainPrefix}}indy.{{ $.Values.ingress.host }}
        - {{ $.Values.ingress.subdomainPrefix}}tails.{{ $.Values.ingress.host }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if $.Values.ingress.exposeAdmin }}
    - host: {{ $.Values.ingress.subdomainPrefix}}indy-admin.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ $fullName }}
              servicePort: 11080
    {{- end }}
    - host: {{ $.Values.ingress.subdomainPrefix}}indy.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ $fullName }}
              servicePort: 11000
          
    - host: {{ $.Values.ingress.subdomainPrefix}}tails.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ $tailsFullName }}
              servicePort: 6543
{{- end }}
