apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssi-aca-py.fullname" . }}
  labels:
    {{- include "ssi-aca-py.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 11000
      targetPort: client
      protocol: TCP
      name: client
    - port: 11080
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "ssi-aca-py.selectorLabels" . | nindent 4 }}
