{{- $fullName := include "ssi-accreditation-controller.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ACCR_MONGODB_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  ACCR_ID_PROVIDER_ACCR_CLIENT_SECRET: {{ .Values.keycloak.clientSecret | b64enc | quote }}
  ACCR_MONGODB_SSL_KEYSTORE: {{ .Values.dbssl.sslKeyStore | default "" | b64enc | quote }}
  ACCR_MONGODB_SSL_KEYSTORE_PASSWORD: {{ .Values.dbssl.sslKeyStorePassword | default "" | b64enc | quote }}
  ACCR_MONGODB_SSL_TRUSTSTORE: {{ .Values.dbssl.sslTrustStore | default "" | b64enc | quote }}
  ACCR_MONGODB_SSL_TRUSTSTORE_PASSWORD: {{ .Values.dbssl.sslKeyStorePassword | default "" | b64enc | quote }}
  ACCR_AGENT_API_KEY: {{ .Values.agent.APIKey | default "" | b64enc | quote }}
  ACCR_AGENT_WEBHOOK_API_KEY: {{ .Values.agent.webHookAPIKey | default "" | b64enc | quote }}
  ACCR_CONTROLLER_SSL_KEYSTORE: {{ .Values.ssl.sslKeyStore | default "" | b64enc | quote }}
  ACCR_CONTROLLER_SSL_KEYSTORE_PASSWORD: {{ .Values.ssl.sslKeyStorePassword | default "" | b64enc | quote }}
  ACCR_CONTROLLER_SSL_KEYSTORE_TYPE: {{ .Values.ssl.sslKeyStoreType | default "" | b64enc | quote }}
  ACCR_CONTROLLER_SSL_KEY_ALIAS: {{ .Values.ssl.sslKeyAlias | default "" | b64enc | quote }}
  ACCR_API_KEY: {{ .Values.APIKey | default "" | b64enc | quote }}
