{{- $fullName := include "ssi-verification-controller.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  VERI_INFO_VERSION: {{ .Chart.Version }}
  VERI_AGENT_PORT_ADMIN: {{ .Values.agent.port | default "11080" | quote }}
  VERI_UI_PORT:	{{ .Values.ui.port | default "4300" | quote }}
  VERI_UI_HOST: {{ .Values.ui.host | default (printf "http://%s-ssi-verification-ui" .Release.Name) | quote }}
  VERI_ID_PROVIDER_PERMISSIONS_PATH:  {{ .Values.overrides.VERI_ID_PROVIDER_PERMISSIONS_PATH | default "auth/realms/{realm}/protocol/openid-connect/token"   | quote }}
  SPRING_PROFILES_ACTIVE:  {{ .Values.overrides.SPRING_PROFILES_ACTIVE | default "localdocker"  | quote }}
  VERI_JWT_USER_IDENTIFIER_ENTRY_NAME:  {{ .Values.overrides.VERI_JWT_USER_IDENTIFIER_ENTRY_NAME | default "preferred_username"   | quote }}
  VERI_ID_PROVIDER_TOKEN_PATH:  {{ .Values.overrides.VERI_ID_PROVIDER_TOKEN_PATH | default "auth/realms/{realm}/protocol/openid-connect/token/introspect"  | quote }}
  AGENT_API_KEY_HEADER_NAME: {{ .Values.overrides.AGENT_API_KEY_HEADER_NAME | default "X-API-Key" | quote }}
  ACCR_API_KEY_HEADER_NAME: {{ .Values.overrides.ACCR_API_KEY_HEADER_NAME | default "X-API-Key" | quote }}
  VERI_INFO_CONTACT_EMAIL: {{ .Values.info.contactEmail | default "" | quote }}
  VERI_INFO_CONTACT_NAME: {{ .Values.info.contactName | default "" | quote }}
  VERI_INFO_CONTACT_URL: {{ .Values.info.contactURL | default "" | quote }}
  VERI_INFO_DESCRIPTION: {{ .Values.info.description | default "" | quote }}
  VERI_INFO_TITLE: {{ .Values.info.title | default "Verification Controller" | quote }}
  VERI_CONTROLLER_PORT: {{ .Values.service.port | default "8080" | quote }}
  VERI_MONGODB_PORT: {{ .Values.overrides.VERI_MONGODB_PORT | default "27017" | quote }}
  VERI_MONGODB_DB_NAME: {{ .Values.mongodb.auth.database }}
  VERI_MONGODB_AUTH_DB_NAME: {{ .Values.mongodb.auth.authDatabase | default .Values.mongodb.auth.database | quote }}
  VERI_MONGODB_HOST:  {{ .Values.mongodb.host | default (printf "%s-mongodb" .Release.Name)  | quote }}
  VERI_MONGODB_USERNAME: {{ .Values.mongodb.host | default (printf "%s-mongodb" .Release.Name)  | quote }}
  VERI_AGENT_NAME:	{{ .Values.overrides.VERI_AGENT_NAME | default "Verification-Agent" | quote }}
  AGENT_DIDCOMM_URL: {{ .Values.agent.didcommURL | default "didcomm://example.org?m=" | quote }}
  VERI_CHECKOUT_DELAY_IN_SECONDS: {{ .Values.guest.checkoutDelay | default "120" | quote }}
  VERI_I18N_PATH: {{ .Values.ui.i18nPath | default "/app/resources/i18n/ui" | quote }}