{{- $fullName := include "ssi-verification-controller.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  VERI_MONGODB_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  VERI_ID_PROVIDER_VERI_CLIENT_SECRET: {{ .Values.keycloak.clientSecret | default "" | b64enc | quote }}
  VERI_MONGODB_SSL_KEYSTORE: {{ .Values.dbssl.sslKeyStore | default "" | b64enc | quote }}
  VERI_MONGODB_SSL_KEYSTORE_PASSWORD: {{ .Values.dbssl.sslKeyStorePassword | default "" | b64enc | quote }}
  VERI_MONGODB_SSL_TRUSTSTORE: {{ .Values.dbssl.sslTrustStore | default "" | b64enc | quote }}
  VERI_MONGODB_SSL_TRUSTSTORE_PASSWORD: {{ .Values.dbssl.sslTrustStorePassword | default "" | b64enc | quote }}
  VERI_AGENT_API_KEY: {{ .Values.agent.APIKey | default "" | b64enc | quote }}
  ACCR_AGENT_WEBHOOK_API_KEY: {{ .Values.accreditation.webHookAPIKey | default "" | b64enc | quote }}
  VERI_AGENT_WEBHOOK_API_KEY: {{ .Values.agent.webHookAPIKey | default "" | b64enc | quote }}
  VERI_AGENT_VERKEY: {{ .Values.agent.verkey | default "" | b64enc | quote }}
  AGENT_ARIES_ATTACH_ID: {{ .Values.agent.ariesAttachID | default "libindy-request-presentation-0" | b64enc | quote }}
  AGENT_ARIES_MESSAGE_TYPE: {{ .Values.agent.ariesType | b64enc | quote }}
  VERI_CONTROLLER_SSL_KEYSTORE: {{ .Values.ssl.sslKeyStore | default "" | b64enc | quote }}
  VERI_CONTROLLER_SSL_KEYSTORE_PASSWORD: {{ .Values.ssl.sslKeyStorePassword | default "" | b64enc | quote }}
  VERI_CONTROLLER_SSL_KEYSTORE_TYPE: {{ .Values.ssl.sslKeyStoreType | default "" | b64enc | quote }}
  VERI_CONTROLLER_SSL_KEY_ALIAS: {{ .Values.ssl.sslKeyAlias | default "" | b64enc | quote }}
  ACCR_API_KEY: {{ .Values.accreditation.apiKey | default "" | b64enc | quote }}